version: "3.9"
services:
  app:
    image: safe_repository:latest
    container_name: app
    depends_on:
      - rabbit
      - mysql
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - app
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    # for M1
    # platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./dbschema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password