version: "3.9"
services:
  app:
    image: safe_repository:latest
    container_name: app
    depends_on:
      - rabbit
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - app
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"